version: "3"

services:

  runtime-setup:
    image: swift-aws-lambda:al2-5.10
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.10-amazonlinux2"

  test:
    image: swift-aws-lambda:al2-5.10

  test-examples:
    image: swift-aws-lambda:al2-5.10

  shell:
    image: swift-aws-lambda:al2-5.10
