# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.al2.6.0.yaml run test

services:

  runtime-setup:
    image: swift-aws-lambda:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: swift-aws-lambda:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code:z
    working_dir: /code
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  soundness:
    <<: *common
    command: >-
      /bin/bash -clx "
      curl -s https://raw.githubusercontent.com/apple/swift-nio/main/scripts/check-swift-format.sh | bash && 
      curl -s https://raw.githubusercontent.com/apple/swift-nio/main/scripts/check-license-header.sh | bash 
      "

  test:
    <<: *common
    command: /bin/bash -cl "swift test -Xswiftc -warnings-as-errors $${SANITIZER_ARG-}"

  test-examples:
    <<: *common
    command: >-
      /bin/bash -clx "
      LAMBDA_USE_LOCAL_DEPS=true swift build --package-path Examples/APIGateway &&
      LAMBDA_USE_LOCAL_DEPS=true swift build --package-path Examples/AWSSDK &&
      LAMBDA_USE_LOCAL_DEPS=true swift build --package-path Examples/HelloWorld &&
      LAMBDA_USE_LOCAL_DEPS=true swift build --package-path Examples/Soto
      "

  # util

  shell:
    <<: *common
    entrypoint: /bin/bash -l
