name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "SwiftAWSLambdaRuntime"
      shell_check_enabled: false
      python_lint_check_enabled: false
      api_breakage_check_container_image: "swift:6.0-noble"
      docs_check_container_image: "swift:6.0-noble"
      format_check_container_image: "swiftlang/swift:nightly-6.0-jammy"

  unit-tests:
    name: Unit tests
    uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
    with:
      linux_5_9_enabled: false
      linux_5_10_enabled: false
      linux_nightly_6_0_arguments_override: "--explicit-target-dependency-import-check error"
      linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error"

  integration-tests:
    name: Integration Tests
    uses: ./.github/workflows/integration_tests.yml
    with:
      name: "Integration tests"
      examples_enabled: true
      matrix_linux_command: "LAMBDA_USE_LOCAL_DEPS=../.. swift build"
      # We pass the list of examples here, but we can't pass an array as argument
      # Instead, we pass a String with a valid JSON array.
      # The workaround is mentioned here https://github.com/orgs/community/discussions/11692
      examples: "[ 'HelloWorld', 'APIGateway','S3_AWSSDK', 'S3_Soto' ]"

      archive_plugin_enabled: true

  swift-6-language-mode:
    name: Swift 6 Language Mode
    uses: apple/swift-nio/.github/workflows/swift_6_language_mode.yml@main
