name: PR

on:
    pull_request:
      types: [opened, reopened, synchronize]

jobs:
    soundness:
        name: Soundness
        uses: apple/swift-nio/.github/workflows/soundness.yml@main
        with:
            license_header_check_project_name: "SwiftAWSLambdaRuntime"
            shell_check_enabled: false
            api_breakage_check_container_image: "swift:6.0-noble"
            docs_check_container_image: "swift:6.0-noble"

    unit-tests:
        name: Unit tests
        uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
        with:
            linux_5_8_enabled: false
            linux_5_9_enabled: false
            linux_5_10_enabled: false
            linux_nightly_6_0_arguments_override: "--explicit-target-dependency-import-check error"
            linux_nightly_main_arguments_override: "--explicit-target-dependency-import-check error"

    integration-tests:
        name: Integration Tests
        uses: ./.github/workflows/examples_matrix.yml
        with:
            # We should pass the list of examples here, but we can't pass an array as argument
            # examples: [ "HelloWorld", "APIGateway" ]
            name: "Integration tests"
            matrix_linux_command: "LAMBDA_USE_LOCAL_DEPS=../.. swift build"
    
    swift-6-language-mode:
        name: Swift 6 Language Mode
        uses: apple/swift-nio/.github/workflows/swift_6_language_mode.yml@main
