name: PR

on:
    pull_request:
      types: [opened, reopened, synchronize]

jobs:
    soundness:
        name: Soundness
        uses: apple/swift-nio/.github/workflows/soundness.yml@main
        with:
            license_header_check_project_name: "SwiftAWSLambdaRuntime"
            # remove "kill killed" from the default list for now
            unacceptable_language_check_word_list:
                "blacklist whitelist slave master sane sanity insane insanity killing hang hung hanged hanging"

    unit-tests:
        name: Unit tests
        uses: apple/swift-nio/.github/workflows/unit_tests.yml@main
        with:
            linux_5_9_arguments_override: "--warnings-as-errors --explicit-target-dependency-import-check error"
            linux_5_10_arguments_override: "--warnings-as-errors --explicit-target-dependency-import-check error"
            linux_nightly_6_0_arguments_override: "--warnings-as-errors --explicit-target-dependency-import-check error"
            linux_nightly_main_arguments_override: "--warnings-as-errors --explicit-target-dependency-import-check error"

    swift-6-language-mode:
        name: Swift 6 Language Mode
        uses: apple/swift-nio/.github/workflows/swift_6_language_mode.yml@main
